server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB
  port: 8080


spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:static/
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB

file-manager:
  thumbnail:
    width: 80 # 缩略图宽
  volumes:
    - Node:
      source: fileSystem # 暂时只支持本地文件系统
      alias: files # 目录别名
      path: /D:/CR # 映射目录
      isDefault: true # 是否默认打开
      locale:
      constraint:
        locked: false # 文件夹是否锁定
        readable: true # 是否可读
        writable: true # 是否可写










